export type AnalyzeErrorCode =
  | "MISSING_OPENAI_API_KEY"
  | "MISSING_GOOGLE_API_KEY"
  | "INVALID_OPENAI_BASE_URL"
  | "INVALID_PROXY_URL"
  | "OPENAI_AUTH_FAILED"
  | "OPENAI_PERMISSION_DENIED"
  | "OPENAI_MODEL_NOT_FOUND"
  | "REQUEST_TOO_LARGE"
  | "OPENAI_CONNECTION_ERROR"
  | "OPENAI_RELAY_CONNECTION_FAILED"
  | "OPENAI_TIMEOUT"
  | "GOOGLE_AUTH_FAILED"
  | "GOOGLE_PERMISSION_DENIED"
  | "GOOGLE_REQUEST_TOO_LARGE"
  | "GOOGLE_CONNECTION_ERROR"
  | "GOOGLE_TIMEOUT"
  | "GOOGLE_API_ERROR"
  | "GOOGLE_UNKNOWN_ERROR"
  | "MISSING_BANANA_API_KEY"
  | "MISSING_BANANA_BASE_URL"
  | "INVALID_BANANA_BASE_URL"
  | "MISSING_RELAY_API_KEY"
  | "MISSING_RELAY_BASE_URL"
  | "INVALID_RELAY_BASE_URL"
  | "IMAGE_MODEL_AUTH_FAILED"
  | "IMAGE_MODEL_NOT_FOUND"
  | "IMAGE_PROHIBITED_CONTENT"
  | "IMAGE_POSTPROCESS_FAILED"
  | "IMAGE_RELAY_NO_IMAGE"
  | "IMAGE_RELAY_CONNECTION_FAILED"
  | "IMAGE_RELAY_TIMEOUT"
  | "BANANA_RELAY_AUTH_FAILED"
  | "BANANA_RELAY_MODEL_NOT_FOUND"
  | "BANANA_RELAY_CONNECTION_FAILED"
  | "BANANA_RELAY_TIMEOUT"
  | "BANANA_RELAY_NO_IMAGE"
  | "NANO_BANANA_NO_IMAGE"
  | "UNSUPPORTED_IMAGE_FORMAT"
  | "GENERATE_API_ERROR"
  | "GENERATE_REQUEST_INVALID"
  | "GPT_JSON_PARSE_FAILED"
  | "ANALYZE_REQUEST_INVALID"
  | "OPENAI_API_ERROR"
  | "OPENAI_UNKNOWN_ERROR"
  | "UNKNOWN_ANALYZE_ERROR";

export type AnalyzeApiError = {
  message: string;
  code: AnalyzeErrorCode;
  debug: string;
};

export class AppApiError extends Error {
  code: AnalyzeErrorCode;
  debug: string;

  constructor(code: AnalyzeErrorCode, message: string, debug: string) {
    super(message);
    this.name = "AppApiError";
    this.code = code;
    this.debug = debug;
  }
}
